---
- name: This play installs needed tools to provision infrastructure VMs
  hosts: vm_host
  vars_files:
    - vars/cluster_vars.yml
    - vars/infra_vars.yml
  become: true
  tasks:
    - name: Install needed packages
      ansible.builtin.yum:
        name: "{{ virtualization_packages.rhel }}"
        state: latest # noqa package-latest
      when:
        - ansible_distribution == 'RedHat'

    - name: Install needed packages
      ansible.builtin.yum:
        name: "{{ virtualization_packages.centos }}"
        state: latest # noqa package-latest
      when:
        - ansible_distribution == 'CentOS'

    - name: Install needed packages
      ansible.builtin.yum:
        name: "{{ virtualization_packages.fedora }}"
        state: latest # noqa package-latest
      when:
        - ansible_distribution == 'Fedora'

    - name: Download and provision Terraform
      ansible.builtin.unarchive:
        src: "{{ terraform_release_url }}"
        dest: /usr/bin/
        mode: "0755"
        remote_src: true

    - name: Virtualization services are enabled
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: true
      when:
        - ansible_distribution != 'CentOS'

    - name: Virtualization services are enabled
      ansible.builtin.service:
        name: virtqemud
        state: started
        enabled: true
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version | int == 9

    - name: Ensuring libvirt module is present
      ansible.builtin.pip:
        name: libvirt-python
      become: true

    - name: Use TF project to ensure pool and network are defined
      community.general.terraform:
        project_path: "{{ workspace_directory.base_path }}/{{ cluster.name }}/terraform/libvirt-resources"
        variables:
          dns: "{{ infra_nodes.host_list.bastion[0].ip }}"
          domain: "{{ cluster.name }}.{{ domain }}"
          network_cidr: ' ["{{ network_cidr }}"]'
          cluster_name: "{{ cluster.name }}"
        force_init: true
        state: present
