---
- name: This play installs needed tools to provision infrastructure VMs
  hosts: vm_host
  vars_files:
    - vars/cluster_vars.yml
  become: true
  tasks:

    - name: Install needed packages
      ansible.builtin.yum:
        name: "{{ virtualization_packages.rhel }}"
        state: latest
      when:
        - ansible_distribution == 'RedHat'

    - name: Install needed packages
      ansible.builtin.yum:
        name: "{{ virtualization_packages.centos8 }}"
        state: latest
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version | int == 8

    - name: Install needed packages
      ansible.builtin.yum:
        name: "{{ virtualization_packages.centos7 }}"
        state: latest
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version | int == 7

    - name: Install needed packages
      ansible.builtin.yum:
        name: "{{ virtualization_packages.fedora }}"
        state: latest
      when:
        - ansible_distribution == 'Fedora'

    - name: Download and provision Terraform
      ansible.builtin.unarchive:
        src: "{{ terraform_release_url }}"
        dest: /usr/bin/
        mode: 755
        remote_src: yes

    - name: Virtualization services are enabled
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: true


    - name: Ensuring libvirt module is present
      ansible.builtin.pip:
        name: libvirt-python
      become: true

    - name: Use TF project to ensure pool and network are defined
      community.general.terraform:
        project_path: "{{ workspace_directory.base_path }}/terraform/libvirt-resources"
        variables:
          domain: "{{ domain }}"
          network_cidr: ' ["{{ network_cidr }}"]'
          cluster_name: "{{ cluster.name }}"
        force_init: true
        state: present
