---
- name: This play installs needed tools to provision infrastructure VMs
  hosts: vm_host
  vars_files:
    - cluster_vars.yml
  tasks:
    - name: Set home directory as fact for the user
      ansible.builtin.set_fact:
        home_dir: "{{ ansible_env.HOME }}"

    - name: Creating workspace
      ansible.builtin.file:
        state: directory
        path: "{{ workspace_directory.base_path }}/{{ cluster.name }}"
        recurse: true

    - name: Copy terraform files on host
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/terraform"
        dest: "{{ workspace_directory.base_path }}/{{ cluster.name }}/"
        mode: "0755"

    - name: Create ssh keypair
      community.crypto.openssh_keypair:
        path: "{{ playbook_dir }}/id_rsa_ocp_setup"
      delegate_to: localhost

    - name: Copy SSH keys in working directory
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ item }}"
        dest: "{{ workspace_directory.base_path }}/{{ cluster.name }}/{{ item }}"
        mode: "0755"
      loop:
        - id_rsa_ocp_setup
        - id_rsa_ocp_setup.pub

    - name: Getting ssh private key
      ansible.builtin.slurp:
        src: "{{ workspace_directory.base_path }}/{{ cluster.name }}/id_rsa_ocp_setup"
      register: service_key

    - name: Getting ssh public key
      ansible.builtin.slurp:
        src: "{{ workspace_directory.base_path }}/{{ cluster.name }}/id_rsa_ocp_setup.pub"
      register: service_key_pub

    - name: Save SSH keys as fact for further use
      ansible.builtin.set_fact:
        ssh_service_key: "{{ service_key['content'] | b64decode }}"
        ssh_service_key_pub: "{{ service_key_pub['content'] | b64decode }}"
