- name: Provisioning infrastructure VMs
  hosts: vm_host
  vars_files:
    - vars/infra_vars.yml
    - vars/libvirt.yml
  tasks:

    - set_fact:
        ocp_domain: "{{ cluster_name }}.{{ domain }}"

    - name: Ensure to clean known_hosts
      known_hosts:
        host: "{{ item.value[0].ip }}" 
        path: ~/.ssh/known_hosts
        state: absent
      loop: "{{ infra_nodes.host_list|dict2items }}"

    - name: Create ssh keypair
      openssh_keypair:
        path: "id_rsa"

    - name: Deploy bastion VM with terraform
      terraform:
        force_init: true
        project_path: "terraform/bastion"
        variables:
          libvirt_network: "{{ libvirt.network.network_name }}"
          libvirt_pool: "{{ libvirt.storage.pool_name }}"
          network_data: "{ hostIP = \"{{ infra_nodes.host_list.bastion[0].ip }}\", broadcast= \"{{ infra_nodes.host_list.bastion[0].ip | ipsubnet(24) | ipaddr('broadcast') }}\", dns = \"{{ infra_nodes.host_list.bastion[0].ip | ipsubnet(24) | ipaddr('network') | ipmath(1) }}\", gateway = \"{{ infra_nodes.host_list.bastion[0].ip | ipsubnet(24) | ipaddr('network') | ipmath(1) }}\", network = \"{{ infra_nodes.host_list.bastion[0].ip | ipsubnet(24) | ipaddr('network') }}\" }"
          hostname: "bastion"
          enable_nfs: "{{ nfs_registry | lower }}"
        state: present
      register: output_ba

    - name: Deploy loadbalancer VM
      terraform:
        force_init: true
        project_path: "terraform/loadbalancer"
        variables:
          libvirt_network: "{{ libvirt.network.network_name }}"
          libvirt_pool: "{{ libvirt.storage.pool_name }}"
          network_data: "{ hostIP = \"{{ infra_nodes.host_list.loadbalancer[0].ip }}\", broadcast= \"{{ infra_nodes.host_list.loadbalancer[0].ip | ipsubnet(24) | ipaddr('broadcast') }}\", dns = \"{{ infra_nodes.host_list.loadbalancer[0].ip | ipsubnet(24) | ipaddr('network') | ipmath(1) }}\", gateway = \"{{ infra_nodes.host_list.loadbalancer[0].ip | ipsubnet(24) | ipaddr('network') | ipmath(1) }}\", network = \"{{ infra_nodes.host_list.loadbalancer[0].ip | ipsubnet(24) | ipaddr('network') }}\" }"
          hostname: "loadbalancer"
        state: present
      register: output_lb

    - name: Add bastion and loadbalancer to in-memory inventory
      add_host:
        hostname: '{{ item.key }}'
        ansible_host: '{{ item.value[0].ip }}'
        ansible_ssh_private_key_file: "id_rsa"
        ansible_user: ocpinstall
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        domain: "{{ domain }}"
        cluster_name: "{{ cluster_name }}"
        ocp_domain: "{{ ocp_domain }}"
        nfs_registry_enabled: "{{ nfs_registry }}"
        timezone: "{{ dhcp.timezone }}"
        ntp_server: "{{ dhcp.ntp }}"
      loop: "{{ infra_nodes.host_list|dict2items }}"


- name: Check connection to infra VMs and set facts
  hosts: bastion,loadbalancer
  gather_facts: no
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection: 
        timeout: 120
        delay: 0
    - ping:

    - setup:
      register: machine_facts

    - set_fact:
        host_ip: "{{ machine_facts.ansible_facts.ansible_default_ipv4.address }}"
        host_interface: "{{ machine_facts.ansible_facts.ansible_default_ipv4.interface }}"
        host_mac: "{{ machine_facts.ansible_facts.ansible_default_ipv4.macaddress }}"
        host_fqdn: "{{ machine_facts.ansible_facts.ansible_fqdn }}"
    
    - set_fact: 
        host_api_fqdn: "api.{{ ocp_domain }}"
        host_api_int_fqdn: "api-int.{{ ocp_domain }}"
        host_apps_fqdn: "apps.{{ ocp_domain }}"  
      when: inventory_hostname == 'loadbalancer'

