---
- name: Creating a workspace on Bastion
  hosts: bastion 
  gather_facts: no
  vars_files:
    - vars/cluster_vars.yml
  tasks:

    - name: Erasing dnsmasq lease
      file:
        path: /var/lib/dnsmasq/dnsmasq.leases
        state: absent
      become: true

    - name: Creating workspace
      file:
        state: directory
        path: "{{ item }}"
      loop: 
        - "{{ workspace_directory.base_path }}/{{ workspace_directory.config_dir }}"
        - "~/.ssh"

    - name: Creating ssh keys if not exists
      openssh_keypair:
        path: "~/.ssh/id_rsa"

    - name: Creating tftpboot and nginx workspace
      file:
        state: directory
        path: "{{ item }}"
      loop: 
        - "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}"
        - "{{ nginx_document_root }}/{{ nginx_workspace_dir }}"
      become: True

    - name: Downloading Openshift installer and CLI
      unarchive:
        src: "{{ item }}"
        dest: /usr/local/bin
        remote_src: yes
      become: True
      loop:
        - "{{ downloads.ocp.base_url + cluster.version + '/' + downloads.ocp.ocp_oc_cli + '-' + cluster.version + '.tar.gz' }}"
        - "{{ downloads.ocp.base_url + cluster.version + '/' + downloads.ocp.ocp_installer + '-' + cluster.version + '.tar.gz' }}"
      when: 
        - not (skip_download | bool) 
        - cluster.version != "latest"
        - cluster.version != "fast"
        - cluster.version != "stable"
        - cluster.version != "candidate"

    - name: Downloading Openshift installer and CLI
      unarchive:
        src: "{{ item }}"
        dest: /usr/local/bin
        remote_src: yes
      become: True
      loop:
        - "{{ downloads.ocp.base_url + cluster.version + '/' + downloads.ocp.ocp_oc_cli + '.tar.gz' }}"
        - "{{ downloads.ocp.base_url + cluster.version + '/' + downloads.ocp.ocp_installer + '.tar.gz' }}"
      when:
        - not (skip_download | bool)
        - cluster.version == "latest" or cluster.version == "fast" or cluster.version == "stable" or cluster.version == "candidate"

    - name: Checking for openshift-install tool
      command: openshift-install version
      register: output
      failed_when: output.rc !=0

    - name: Checking for OCP cli tool
      command: oc
      register: output
      failed_when: output.rc !=0

    - block:
        - name: Retrieve the minor version
          set_fact: 
            version: "{{ cluster.version.split('.') }}"

        - block:
            - name: Download initramfs and kernel 
              get_url:
                url: "{{ downloads.rhcos.41.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
              loop:
                - "{{ downloads.rhcos.41.initramfs }}"
                - "{{ downloads.rhcos.41.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              get_url:
                url:  "{{ downloads.rhcos.41.base_url + downloads.rhcos.41.coreos }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.41.coreos }}"
      
            - name: Set fact for files
              set_fact:
                rhcos_kernel: "{{ downloads.rhcos.41.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.41.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.41.coreos }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 1

        - block:
            - name: Download initramfs and kernel
              get_url:
                url: "{{ downloads.rhcos.42.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
              loop:
                - "{{ downloads.rhcos.42.initramfs }}"
                - "{{ downloads.rhcos.42.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              get_url:
                url:  "{{ downloads.rhcos.42.base_url + downloads.rhcos.42.coreos }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.42.coreos }}"
            - name: Set fact for files
              set_fact:
                rhcos_kernel: "{{ downloads.rhcos.42.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.42.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.42.coreos }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 2

        - block:
            - name: Download initramfs and kernel
              get_url:
                url: "{{ downloads.rhcos.43.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
              loop:
                - "{{ downloads.rhcos.43.initramfs }}"
                - "{{ downloads.rhcos.43.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              get_url:
                url:  "{{ downloads.rhcos.43.base_url + downloads.rhcos.43.coreos }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.43.coreos }}"

            - name: Set fact for files
              set_fact:
                rhcos_kernel: "{{ downloads.rhcos.43.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.43.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.43.coreos }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 3

        - block:
            - name: Download initramfs and kernel
              get_url:
                url: "{{ downloads.rhcos.44.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
              loop:
                - "{{ downloads.rhcos.44.initramfs }}"
                - "{{ downloads.rhcos.44.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              get_url:
                url:  "{{ downloads.rhcos.44.base_url + downloads.rhcos.44.coreos }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.44.coreos }}"

            - name: Set fact for files
              set_fact:
                rhcos_kernel: "{{ downloads.rhcos.44.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.44.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.44.coreos }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 4

        - block:
            - name: Download initramfs and kernel
              get_url:
                url: "{{ downloads.rhcos.45.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
              loop:
                - "{{ downloads.rhcos.45.initramfs }}"
                - "{{ downloads.rhcos.45.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              get_url:
                url:  "{{ downloads.rhcos.45.base_url + downloads.rhcos.45.coreos }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.45.coreos }}"

            - name: Set fact for files
              set_fact:
                rhcos_kernel: "{{ downloads.rhcos.45.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.45.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.45.coreos }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 5

        - block:
            - name: Download initramfs and kernel
              get_url:
                url: "{{ downloads.rhcos.46.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
              loop:
                - "{{ downloads.rhcos.46.initramfs }}"
                - "{{ downloads.rhcos.46.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              get_url:
                url:  "{{ downloads.rhcos.46.base_url + downloads.rhcos.46.rootfs }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.46.rootfs }}"

            - name: Set fact for files
              set_fact:
                rhcos_kernel: "{{ downloads.rhcos.46.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.46.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.46.rootfs }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 6

        - block:
            - name: Download initramfs and kernel
              get_url:
                url: "{{ downloads.rhcos.47.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
              loop:
                - "{{ downloads.rhcos.47.initramfs }}"
                - "{{ downloads.rhcos.47.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              get_url:
                url:  "{{ downloads.rhcos.47.base_url + downloads.rhcos.47.rootfs }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.47.rootfs }}"

            - name: Set fact for files
              set_fact:
                rhcos_kernel: "{{ downloads.rhcos.47.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.47.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.47.rootfs }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 7

        - block:
            - name: Download initramfs and kernel
              get_url:
                url: "{{ downloads.rhcos.48.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
              loop:
                - "{{ downloads.rhcos.48.initramfs }}"
                - "{{ downloads.rhcos.48.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              get_url:
                url:  "{{ downloads.rhcos.48.base_url + downloads.rhcos.48.rootfs }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.48.rootfs }}"

            - name: Set fact for files
              set_fact:
                rhcos_kernel: "{{ downloads.rhcos.48.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.48.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.48.rootfs }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 8

        - block:
            - name: Download initramfs and kernel
              get_url:
                url: "{{ downloads.rhcos.49.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
              loop:
                - "{{ downloads.rhcos.49.initramfs }}"
                - "{{ downloads.rhcos.49.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              get_url:
                url:  "{{ downloads.rhcos.49.base_url + downloads.rhcos.49.rootfs }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.49.rootfs }}"

            - name: Set fact for files
              set_fact:
                rhcos_kernel: "{{ downloads.rhcos.49.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.49.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.49.rootfs }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 9

        - block:
            - name: Download initramfs and kernel
              get_url:
                url: "{{ downloads.rhcos.410.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
              loop:
                - "{{ downloads.rhcos.410.initramfs }}"
                - "{{ downloads.rhcos.410.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              get_url:
                url:  "{{ downloads.rhcos.410.base_url + downloads.rhcos.410.rootfs }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.410.rootfs }}"

            - name: Set fact for files
              set_fact:
                rhcos_kernel: "{{ downloads.rhcos.410.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.410.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.410.rootfs }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 10

      when: 
        - not (skip_download | bool) 
        - cluster.version != "stable"
      
      become: true

    - block:
      - name: Retrieve the minor version
        set_fact:
          version: 
            0: 4
            1: 99
      - name: Download initramfs and kernel
        get_url:
          url: "{{ downloads.rhcos.stable.base_url + item }}"
          dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
        loop:
          - "{{ downloads.rhcos.stable.initramfs }}"
          - "{{ downloads.rhcos.stable.kernel }}"

      - name: Download Red Hat CoreOS for bare metal
        get_url:
          url:  "{{ downloads.rhcos.stable.base_url + downloads.rhcos.stable.rootfs }}"
          dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.stable.rootfs }}"

      - name: Set fact for files
        set_fact:
          rhcos_kernel: "{{ downloads.rhcos.stable.kernel }}"
          rhcos_initramfs: "{{ downloads.rhcos.stable.initramfs }}"
          rhcos_os: "{{ downloads.rhcos.stable.rootfs }}"
      become: true
      when: 
        - not (skip_download | bool)
        - cluster.version == "stable"
