---
- name: Creating a workspace on Bastion
  hosts: bastion
  vars_files:
    - vars/cluster_vars.yml
  tasks:
    - name: Erasing dnsmasq lease
      ansible.builtin.file:
        path: /var/lib/dnsmasq/dnsmasq.leases
        state: absent
      become: true

    - name: Creating workspace
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        mode: 0755
      loop:
        - "{{ workspace_directory.base_path }}/{{ cluster.name }}/{{ workspace_directory.config_dir }}"
        - "~/.ssh"

    - name: Creating ssh keys if it doens not exist
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_rsa"

    - name: Creating tftpboot and nginx workspace
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        mode: 0755
      loop:
        - "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}"
        - "{{ nginx_document_root }}/{{ nginx_workspace_dir }}"
      become: true

    - name: Downloading Openshift installer and CLI
      ansible.builtin.unarchive:
        src: "{{ item }}"
        dest: /usr/bin
        remote_src: true
      become: true
      loop:
        - "{{ downloads.ocp.base_url }}/{{ cluster.version }}/openshift-client-linux-{{ cluster.version }}.tar.gz"
        - "{{ downloads.ocp.base_url }}/{{ cluster.version }}/openshift-install-linux-{{ cluster.version }}.tar.gz"
      when:
        - not (skip_download | bool)
        - cluster.version != "latest"
        - cluster.version != "fast"
        - cluster.version != "stable"
        - cluster.version != "candidate"

    - name: Downloading Openshift installer and CLI
      ansible.builtin.unarchive:
        src: "{{ item }}"
        dest: /usr/bin
        remote_src: true
      become: true
      loop:
        - "{{ downloads.ocp.base_url }}/{{ cluster.version }}/openshift-client-linux.tar.gz"
        - "{{ downloads.ocp.base_url }}/{{ cluster.version }}/openshift-install-linux.tar.gz"
      when:
        - not (skip_download | bool)
        - cluster.version == "latest" or cluster.version == "fast" or cluster.version == "stable" or cluster.version == "candidate"

    - name: Checking for openshift-install tool
      ansible.builtin.shell: openshift-install version
      register: output
      failed_when: output.rc !=0

    - name: Checking for OCP cli tool
      ansible.builtin.shell: oc
      register: output
      failed_when: output.rc !=0

    - name: Take care of retrieving packages for CoreOS
      block:
        - name: Retrieve the minor version
          ansible.builtin.set_fact:
            version: "{{ cluster.version.split('.') }}"

        - name: Take care of retrieving packages for CoreOS
          block:
            - name: Download initramfs and kernel
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.41.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
                mode: 0755
              loop:
                - "{{ downloads.rhcos.41.initramfs }}"
                - "{{ downloads.rhcos.41.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.41.base_url + downloads.rhcos.41.coreos }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.41.coreos }}"
                mode: 0755

            - name: Set fact for files
              ansible.builtin.set_fact:
                rhcos_kernel: "{{ downloads.rhcos.41.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.41.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.41.coreos }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 1

        - name: Take care of retrieving packages for CoreOS
          block:
            - name: Download initramfs and kernel
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.42.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
                mode: 0755
              loop:
                - "{{ downloads.rhcos.42.initramfs }}"
                - "{{ downloads.rhcos.42.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.42.base_url + downloads.rhcos.42.coreos }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.42.coreos }}"
                mode: 0755
            - name: Set fact for files
              ansible.builtin.set_fact:
                rhcos_kernel: "{{ downloads.rhcos.42.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.42.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.42.coreos }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 2

        - name: Take care of retrieving packages for CoreOS
          block:
            - name: Download initramfs and kernel
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.43.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
                mode: 0755
              loop:
                - "{{ downloads.rhcos.43.initramfs }}"
                - "{{ downloads.rhcos.43.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.43.base_url + downloads.rhcos.43.coreos }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.43.coreos }}"
                mode: 0755

            - name: Set fact for files
              ansible.builtin.set_fact:
                rhcos_kernel: "{{ downloads.rhcos.43.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.43.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.43.coreos }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 3

        - name: Take care of retrieving packages for CoreOS
          block:
            - name: Download initramfs and kernel
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.44.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
                mode: 0755
              loop:
                - "{{ downloads.rhcos.44.initramfs }}"
                - "{{ downloads.rhcos.44.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.44.base_url + downloads.rhcos.44.coreos }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.44.coreos }}"
                mode: 0755

            - name: Set fact for files
              ansible.builtin.set_fact:
                rhcos_kernel: "{{ downloads.rhcos.44.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.44.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.44.coreos }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 4

        - name: Take care of retrieving packages for CoreOS
          block:
            - name: Download initramfs and kernel
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.45.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
                mode: 0755
              loop:
                - "{{ downloads.rhcos.45.initramfs }}"
                - "{{ downloads.rhcos.45.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.45.base_url + downloads.rhcos.45.coreos }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.45.coreos }}"
                mode: 0755

            - name: Set fact for files
              ansible.builtin.set_fact:
                rhcos_kernel: "{{ downloads.rhcos.45.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.45.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.45.coreos }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 5

        - name: Take care of retrieving packages for CoreOS
          block:
            - name: Download initramfs and kernel
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.46.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
                mode: 0755
              loop:
                - "{{ downloads.rhcos.46.initramfs }}"
                - "{{ downloads.rhcos.46.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.46.base_url + downloads.rhcos.46.rootfs }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.46.rootfs }}"
                mode: 0755

            - name: Set fact for files
              ansible.builtin.set_fact:
                rhcos_kernel: "{{ downloads.rhcos.46.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.46.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.46.rootfs }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 6

        - name: Take care of retrieving packages for CoreOS
          block:
            - name: Download initramfs and kernel
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.47.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
                mode: 0755
              loop:
                - "{{ downloads.rhcos.47.initramfs }}"
                - "{{ downloads.rhcos.47.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.47.base_url + downloads.rhcos.47.rootfs }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.47.rootfs }}"
                mode: 0755

            - name: Set fact for files
              ansible.builtin.set_fact:
                rhcos_kernel: "{{ downloads.rhcos.47.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.47.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.47.rootfs }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 7

        - name: Take care of retrieving packages for CoreOS
          block:
            - name: Download initramfs and kernel
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.48.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
                mode: 0755
              loop:
                - "{{ downloads.rhcos.48.initramfs }}"
                - "{{ downloads.rhcos.48.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.48.base_url + downloads.rhcos.48.rootfs }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.48.rootfs }}"
                mode: 0755

            - name: Set fact for files
              ansible.builtin.set_fact:
                rhcos_kernel: "{{ downloads.rhcos.48.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.48.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.48.rootfs }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 8

        - name: Take care of retrieving packages for CoreOS
          block:
            - name: Download initramfs and kernel
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.49.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
                mode: 0755
              loop:
                - "{{ downloads.rhcos.49.initramfs }}"
                - "{{ downloads.rhcos.49.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.49.base_url + downloads.rhcos.49.rootfs }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.49.rootfs }}"
                mode: 0755

            - name: Set fact for files
              ansible.builtin.set_fact:
                rhcos_kernel: "{{ downloads.rhcos.49.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.49.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.49.rootfs }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 9

        - name: Take care of retrieving packages for CoreOS
          block:
            - name: Download initramfs and kernel
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.410.base_url + item }}"
                dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
                mode: 0755
              loop:
                - "{{ downloads.rhcos.410.initramfs }}"
                - "{{ downloads.rhcos.410.kernel }}"

            - name: Download Red Hat CoreOS for bare metal
              ansible.builtin.get_url:
                url: "{{ downloads.rhcos.410.base_url + downloads.rhcos.410.rootfs }}"
                dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.410.rootfs }}"
                mode: 0755

            - name: Set fact for files
              ansible.builtin.set_fact:
                rhcos_kernel: "{{ downloads.rhcos.410.kernel }}"
                rhcos_initramfs: "{{ downloads.rhcos.410.initramfs }}"
                rhcos_os: "{{ downloads.rhcos.410.rootfs }}"

          when:
            - version.0 | int == 4
            - version.1 | int == 10

      when:
        - not (skip_download | bool)
        - cluster.version != "stable"

      become: true

    - name: Take care of retrieving packages for CoreOS
      block:
        - name: Retrieve the minor version
          ansible.builtin.set_fact:
            version:
              0: 4
              1: 99
        - name: Download initramfs and kernel
          ansible.builtin.get_url:
            url: "{{ downloads.rhcos.stable.base_url + item }}"
            dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
            mode: 0755
          loop:
            - "{{ downloads.rhcos.stable.initramfs }}"
            - "{{ downloads.rhcos.stable.kernel }}"

        - name: Download Red Hat CoreOS for bare metal
          ansible.builtin.get_url:
            url: "{{ downloads.rhcos.stable.base_url + downloads.rhcos.stable.rootfs }}"
            dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.stable.rootfs }}"
            mode: 0755

        - name: Set fact for files
          ansible.builtin.set_fact:
            rhcos_kernel: "{{ downloads.rhcos.stable.kernel }}"
            rhcos_initramfs: "{{ downloads.rhcos.stable.initramfs }}"
            rhcos_os: "{{ downloads.rhcos.stable.rootfs }}"
      become: true
      when:
        - not (skip_download | bool)
        - cluster.version == "stable"
