- name: Bastion services configuration
  hosts: bastion
  gather_facts: no
  become: true
  vars_files:
    - vars/infra_vars.yml
    - vars/cluster_vars.yml

  tasks:
    - name: Ensuring tftp boot directory exists
      file:
        state: directory
        path: "{{ tftp_boot_root }}/pxelinux.cfg"

    - name: Copy pxelinux.0 file
      copy:
        src: /usr/share/syslinux/{{ item }}
        dest: "{{ tftp_boot_root }}/"
        remote_src: yes
      loop: "{{ pxe_files }}"

    - name: Creating seelinux rules for dnsmasq service
      copy:
        src: files/my-dnsmasq.pp
        dest: /tmp

    - name: Apply seelinux rules for dnsmasq service
      command: semodule -X 300 -i /tmp/my-dnsmasq.pp 

    - name: Delete selinux temp file
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/my-dnsmasq.pp
        - /tmp/my-dnsmasq.te 

    - name: Firing dnsmasq template
      template:
        src: templates/dnsmasq.j2
        dest: /etc/dnsmasq.conf

    - block:
      - name: Firing pxe boot template
        template:
          src: templates/pxeboot_mac.j2
          dest: "{{ tftp_boot_root }}/pxelinux.cfg/01-{{ hostvars[item].node_mac | replace(':','-') }}"
        loop: "{{ groups['masters'] }}"

      - name: Firing pxe boot template
        template:
          src: templates/pxeboot_mac.j2
          dest: "{{ tftp_boot_root }}/pxelinux.cfg/01-{{ hostvars[item].node_mac | replace(':','-') }}"
        loop: "{{ groups['bootstrap'] }}"

      - name: Firing pxe boot template
        template:
          src: templates/pxeboot_mac.j2
          dest: "{{ tftp_boot_root }}/pxelinux.cfg/01-{{ hostvars[item].node_mac | replace(':','-') }}"
        loop: "{{ groups['workers'] }}"
      when: hostvars['bastion'].version.1 | int >= 6

    - block:
      - name: Firing pxe boot template
        template:
          src: templates/pxeboot_mac_pre-4.6.j2
          dest: "{{ tftp_boot_root }}/pxelinux.cfg/01-{{ hostvars[item].node_mac | replace(':','-') }}"
        loop: "{{ groups['masters'] }}"

      - name: Firing pxe boot template
        template:
          src: templates/pxeboot_mac_pre-4.6.j2
          dest: "{{ tftp_boot_root }}/pxelinux.cfg/01-{{ hostvars[item].node_mac | replace(':','-') }}"
        loop: "{{ groups['bootstrap'] }}"

      - name: Firing pxe boot template
        template:
          src: templates/pxeboot_mac_pre-4.6.j2
          dest: "{{ tftp_boot_root }}/pxelinux.cfg/01-{{ hostvars[item].node_mac | replace(':','-') }}"
        loop: "{{ groups['workers'] }}"
      when: hostvars['bastion'].version.1 | int <= 5

    - name: Configure {{ host_interface }} to use {{ host_ip }} as DNS server
      command: nmcli con mod {{ host_interface }} ipv4.dns "{{ host_ip }}" 

    - name: Refreshing {{ host_interface }}
      shell: nmcli con down "{{ host_interface }}"; nmcli con up "{{ host_interface }}"
                
    - name: Enable services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - dnsmasq
        - nginx

    - name: Enable nfs if needed
      service:
        name: nfs-server
        state: started
        enabled: true
      when: nfs_registry_enabled

    - name: Rebooting bastion
      reboot:
