---
- name: PXE boot vms
  hosts: vm_host
  become: true
  vars_files:
    - vars/cluster_vars.yml
  tasks:
    - name: Restart NetworkManager service
      ansible.builtin.service:
        name: NetworkManager
        state: restarted

    - name: Restart OCP VMs sequentially
      block:
        - name: Shutdown bootstrap node
          community.libvirt.virt:
            name: "{{ hostvars[item].node_hostname }}"
            state: destroyed
          loop: "{{ groups['bootstrap'] }}"

        - name: Shutdown master nodes
          community.libvirt.virt:
            name: "{{ hostvars[item].node_hostname }}"
            state: destroyed
          loop: "{{ groups['masters'] }}"

        - name: Shutdown worker nodes
          community.libvirt.virt:
            name: "{{ hostvars[item].node_hostname }}"
            state: destroyed
          loop: "{{ groups['workers'] }}"
          when: not three_node

        - name: Restart bootstrap node
          community.libvirt.virt:
            name: "{{ hostvars[item].node_hostname }}"
            state: running
          loop: "{{ groups['bootstrap'] }}"

        - name: Restart master nodes
          community.libvirt.virt:
            name: "{{ hostvars[item].node_hostname }}"
            state: running
          loop: "{{ groups['masters'] }}"

        - name: Restart worker nodes
          community.libvirt.virt:
            name: "{{ hostvars[item].node_hostname }}"
            state: running
          loop: "{{ groups['workers'] }}"
          when: not three_node

    - name: State message
      ansible.builtin.debug:
        msg: All VMs are booting...
