- name: Create admin with cluster admin privileges
  hosts: bastion
  vars_files: vars/cluster_vars.yml
  tasks:
    - name: Ensuring httpd-tools is present
      ansible.builtin.dnf:
        name: httpd-tools
        state: present
      become: true

    - name: Ensure pip is up to date
      ansible.builtin.pip:
        name: pip
        state: latest
      become: true

    - name: Ensuring passlib is present
      ansible.builtin.pip:
        name:
          - passlib
          - bcrypt
      become: true

    - name: Firing yaml configuration template for htpasswd identity provider
      ansible.builtin.template:
        src: templates/htpasswd_provider.j2
        dest: "{{ workspace_directory.base_path }}/{{ cluster.name }}/htpasswd_provider.yaml"
        mode: "0755"

    - name: Firing configuration script template for user creation
      ansible.builtin.template:
        src: templates/ocp_user_script.j2
        dest: /tmp/ocp_user.sh
        mode: +x

    - name: Creating htpasswd identity and user
      ansible.builtin.shell: /tmp/ocp_user.sh

    - name: Sleeping 180 seconds...
      ansible.builtin.pause:
        seconds: 240

    - name: Try to login with admin
      ansible.builtin.command: /usr/bin/oc login --insecure-skip-tls-verify -u {{ cluster.ocp_user }} -p {{ cluster.ocp_pass }} https://api.{{ hostvars['bastion'].ocp_domain }}:6443
      retries: 10

    - name: Remove kubeadmin user
      ansible.builtin.shell: /usr/bin/oc delete secrets kubeadmin -n kube-system
