---
- name: Patch worker nodes
  hosts: bastion
  tasks:
    - name: Set fact if infra patching is needed
      set_fact:
        infra_present: true
      when: (groups['infra'] | count > 0)

    - block: 

        - name: Create machine config pool 
          copy:
            src: files/machineconfigpool.yml
            dest: "{{ workspace_directory.base_path }}/machineconfigpool.yml"

        - name: Creating persistent volume for registry
          command: /usr/local/bin/oc create -f {{ workspace_directory.base_path }}/machineconfigpool.yml --config={{ workspace_directory.base_path }}/config/auth/kubeconfig

        - name: Copy label nodes script
          template: 
            src: templates/label_nodes.j2
            dest: /tmp/label_nodes.sh
            mode: +x

        - name: Applying patch
          command: /tmp/label_nodes.sh

        - name: Deleting temp files
          file:
            path: /tmp/label_nodes.sh
            state: absent

        - name: Set default nodeSelector
          template:
            src: templates/patch_default_selector.j2
            dest: /tmp/patch_default_selector.sh
            mode: +x
        - name: Execute script 
          command: /tmp/patch_default_selector.sh

        - name: Delete script
          file:
            path: /tmp/patch_default_selector.sh
            state: absent

      when: infra_present
