---
- name: Cleanup playbook
  hosts: vm_host
  vars_files:
    - vars/libvirt.yml
    - vars/infra_vars.yml
    - vars/cluster_vars.yml
  become: true
  tasks:

    - name: Destroy support VM
      community.general.terraform:
        force_init: true
        project_path: "{{ workspace_directory.base_path }}/terraform/{{ item }}"
        state: absent
        variables:
          sshKey: "{{ playbook_dir }}"
      loop:
        - bastion
        - loadbalancer

    - name: Destroy cluster VM
      community.general.terraform:
        force_init: true
        project_path: "{{ workspace_directory.base_path }}/terraform/{{ item }}"
        state: absent
      loop:
        - bootstrap
        - workers
        - masters
        - sno


    - name: Use TF project to ensure pool and network are removed
      community.general.terraform:
        project_path: "{{ workspace_directory.base_path }}/terraform/libvirt-resources"
        variables:
          domain: "{{ domain }}"
          network_cidr: ' ["{{ libvirt.network.network_cidr }}"]'
          cluster_name: "{{ cluster.name }}"
        force_init: true
        state: absent

    - name: Delete all created paths
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: 
        - /usr/bin/terraform
        - /usr/local/bin/openshift-baremetal-install
        - "{{ workspace_directory.base_path }}"
        - /etc/NetworkManager/conf.d/{{ cluster.name }}-localdns.conf
        - /etc/NetworkManager/dnsmasq.d/{{ cluster.name }}-libvirt_dnsmasq.conf
