- name: This play provisions OCP VMs based on intial config
  hosts: localhost
  tasks:
    # Fail fast if there is any incoherence with nodes

    - fail: 
        msg: "Only ONE bootstrap node can be present"
      when: cluster_nodes.host_list.bootstrap | count > 1

    - fail: 
        msg: "Please check the host_list variable in cluster_nodes"
      when: cluster_nodes.host_list.masters | count <= 0 or cluster_nodes.host_list.workers | count <= 0

    - terraform:
        force_init: true
        project_path: "terraform/bootstrap"
        variables:
          hostname: "bootstrap"
          vm_count: "{{ cluster_nodes.host_list.bootstrap | count }}"
        state: present
      register: output_bootstrap

    - terraform:
        project_path: "terraform/masters"
        force_init: true
        variables:
          hostname: "master"
          vm_count: "{{ cluster_nodes.host_list.masters | count }}"
        state: present
      register: output_masters

    - terraform:
        project_path: "terraform/workers"
        force_init: true
        variables:
          hostname: "worker"
          vm_count: "{{ cluster_nodes.host_list.workers | count }}"
        state: present
      register: output_workers

    - name: Add bootstrap node and set vars
      add_host:
        hostname: 'bootstrap'
        node_hostname: 'bootstrap'
        node_mac: "{{ output_bootstrap.outputs.macs.value[0]|lower }}"
        node_ip: "{{ item.ip }}"
        node_reversedns: "{{ item.ip | ipaddr('revdns') }}"
        node_role: "bootstrap"
        node_fqdn: bootstrap.{{ initial_config.cluster_name }}.{{ initial_config.domain }}
        groups:
          - "bootstrap"
      loop: "{{ cluster_nodes.host_list.bootstrap }}"

    - name: Add masters to given group
      add_host:
        hostname: 'master-{{ master_idx }}'
        node_hostname: 'master-{{ master_idx }}'
        etcd_fqdn: 'etcd-{{ master_idx }}.{{ initial_config.cluster_name }}.{{ initial_config.domain }}'
        etcd_ip: '{{ item.ip }}'
        node_mac: "{{ output_masters.outputs.macs.value[master_idx]|lower }}"
        node_ip: "{{ item.ip }}"
        node_reversedns: "{{ item.ip | ipaddr('revdns') }}"
        node_role: "master"
        node_fqdn: master-{{ master_idx }}.{{ initial_config.cluster_name }}.{{ initial_config.domain }} 
        groups:
          - "masters"
      loop: "{{ cluster_nodes.host_list.masters }}"
      loop_control:
        index_var: master_idx

    - name: Add workers to given group
      add_host:
        hostname: 'worker-{{ worker_idx }}'
        node_hostname: 'worker-{{ worker_idx }}'
        node_mac: "{{ output_workers.outputs.macs.value[worker_idx]|lower }}"
        node_ip: "{{ item.ip }}"
        node_reversedns: "{{ item.ip | ipaddr('revdns') }}"
        node_role: "worker"
        node_fqdn: worker-{{ worker_idx }}.{{ initial_config.cluster_name }}.{{ initial_config.domain }}
        groups:
          - "workers"
      loop: "{{ cluster_nodes.host_list.workers }}"
      loop_control:
        index_var: worker_idx

