packages:
  fedora:
    - syslinux
    - dnsmasq-2.80-10.fc31.x86_64
    - nginx
    - cronie
    - cronie-anacron
    - python-netaddr
    - firewalld

  centos:
    - python36
    - syslinux
    - dnsmasq
    - nginx
    - cronie
    - cronie-anacron
    - tar
    - bind-utils
    - firewalld
